---
- name: check if powerline fonts are installed
  stat:
    path: "{{ ansible_user_dir}}/.local/share/fonts/Roboto Mono for Powerline.ttf"
  register: powerline_installed

- name: retrieve powerline fonts
  git:
    repo: "https://github.com/powerline/fonts.git"
    dest: "{{ powerline_fonts_temp_directory }}"
    depth: 1
    version: a44abd0e742ad6e7fd8d8bc4c3cad5155c9f3a92
  when: not powerline_installed.stat.exists

- name: install powerline fonts
  shell: "cd {{ powerline_fonts_temp_directory }} && sh ./install.sh"
  when: not powerline_installed.stat.exists


- name: cleanup powerline-fonts directory
  file:
    path: "{{ powerline_fonts_temp_directory }}"
    state: absent
  when: not powerline_installed.stat.exists
